import { NextResponse } from "next/server"

const words = [
  "mystery",
  "adventure",
  "romance",
  "science",
  "history",
  "fantasy",
  "biography",
  "poetry",
  "philosophy",
  "art",
  "travel",
  "cooking",
  "nature",
  "technology",
  "music",
  "sports",
  "politics",
  "economics",
  "psychology",
  "education",
  "architecture",
  "cinema",
  "literature",
  "mythology",
  "astronomy",
  "medicine",
  "engineering",
  "mathematics",
  "geography",
  "linguistics",
  "robotics",
  "fashion",
  "design",
  "business",
  "marketing",
  "photography",
  "sociology",
  "anthropology",
  "theology",
  "archaeology",
  "chemistry",
  "physics",
  "biology",
  "ecology",
  "genetics",
  "neuroscience",
  "cybersecurity",
  "cryptography",
  "ethics",
  "law",
  "government",
  "diplomacy",
  "warfare",
  "strategy",
  "alchemy",
  "meditation",
  "self-improvement",
  "motivation",
  "productivity",
  "leadership",
  "entrepreneurship",
  "investing",
  "cryptocurrency",
  "blockchain",
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "quantum computing",
  "astrophysics",
  "meteorology",
  "oceanography",
  "cartography",
  "urban planning",
  "sustainability",
  "agriculture",
  "horticulture",
  "forestry",
  "wildlife",
  "zoology",
  "paleontology",
  "microbiology",
  "biochemistry",
  "nanotechnology",
  "space exploration",
  "aviation",
  "automobiles",
  "railways",
  "ships",
  "submarines",
  "gadgets",
  "video games",
  "board games",
  "puzzles",
  "mysticism",
  "tarot",
  "numerology",
  "horoscopes",
  "superstitions",
  "folklore",
  "fairy tales",
  "legends",
  "conspiracies",
  "urban legends",
  "psychic abilities",
  "extraterrestrials",
  "time travel",
  "parallel universes",
  "dystopia",
  "utopia",
  "steampunk",
  "cyberpunk",
  "biopunk",
  "solarpunk",
  "futurism",
  "retro futurism",
  "minimalism",
  "maximalism",
  "surrealism",
  "cubism",
  "impressionism",
  "realism",
  "expressionism",
  "romanticism",
  "baroque",
  "renaissance",
  "gothic",
  "art deco",
  "calligraphy",
  "graffiti",
  "street art",
  "tattooing",
  "pottery",
  "sculpture",
  "glassblowing",
  "carpentry",
  "blacksmithing",
  "knitting",
  "weaving",
  "origami",
  "animation",
  "puppetry",
  "theater",
  "opera",
  "ballet",
  "jazz",
  "classical music",
  "hip-hop",
  "rock",
  "metal",
  "blues",
  "folk",
  "reggae",
  "country",
  "EDM",
  "lo-fi",
]

export async function GET() {
  const randomWord = words[Math.floor(Math.random() * words.length)]
  return NextResponse.json({ word: randomWord })
}
